language: ruby
rvm:
  - 2.3.0
script:
 - bundle exec rake db:create
 - bundle exec rake db:migrate
 - bundle exec rake db:seed
 - bundle exec rake spec
 - bundle exec rake cucumber

deploy:
  provider: heroku
  api_key: dc4adac0-6490-4e98-b3f0-aa1adafd0ee8
  app:
    Sprint1: SERLER_production
  on:
    all_branches: true
    repo: SDM2016AUT/SERLER_production


